import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const base = "https://adastrabcv.com";
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/wp-content/uploads/*.jpg$",
          "/wp-content/uploads/*.jpeg$",
          "/wp-content/uploads/*.png$",
          "/wp-content/uploads/*.webp$",
          "/wp-content/uploads/*.svg$",
          "/wp-content/themes/",
          "/wp-includes/*.css$",
          "/wp-includes/*.js$",
        ],
        disallow: [
          "/api/",
          "/_next/",
          "/admin/",
          "/wp-login.php",
          "/wp-register.php",
          "/wp-includes/",
          "/wp-content/cache/",
          "/wp-content/plugins/",
          "/wp-content/litespeed/",
          "/xmlrpc.php",
          "/*?*",
          "/*&*",
          "/license.txt",
          "/cgi-bin/",
          "/vendor/",
          "/*?utm_=",
          "/*?fbclid=",
          "/*?gclid=",
          "/*?ref=",
          "/*?session=",
          "/*?pop_up=",
          "/feed/",
          "/comments/feed/",
          "/trackback/",
          "/readme.html",
        ],
      },
      {
        userAgent: ["GPTBot", "ChatGPT-User", "OAI-SearchBot"],
        allow: "/",
      },
      {
        userAgent: ["Googlebot", "Googlebot-Image", "Googlebot-Video", "Googlebot-News"],
        allow: "/",
      },
      {
        userAgent: ["Bingbot", "BingPreview", "MicrosoftPreview", "CopilotBot"],
        allow: "/",
      },
      {
        userAgent: "ClaudeBot",
        allow: "/",
      },
      {
        userAgent: "PerplexityBot",
        allow: "/",
      },
      {
        userAgent: ["Applebot", "Applebot-Extended"],
        allow: "/",
      },
      {
        userAgent: ["FacebookBot", "Meta-ExternalAgent", "Meta-ExternalFetcher"],
        allow: "/",
      },
      {
        userAgent: "Amazonbot",
        allow: "/",
      },
      {
        userAgent: ["Yandex", "YandexBot"],
        allow: "/",
      },
      {
        userAgent: "DuckDuckBot",
        allow: "/",
      },
      {
        userAgent: "Baiduspider",
        allow: "/",
      },
      {
        userAgent: [
          "CazoodleBot",
          "MJ12bot",
          "Gigabot",
          "01h4x.com",
          "360Spider",
          "404checker",
          "404enemy",
          "80legs",
          "Abonti",
          "Aboundex",
          "Aboundexbot",
          "Acunetix",
          "ADmantX",
          "adscanner",
          "AfD-Verbotsverfahren",
          "Alexibot",
          "Alligator",
          "AllSubmitter",
          "AlphaBot",
          "Anarchie",
          "Anarchy",
          "Anarchy99",
          "Ankit",
          "Anthill",
          "Apexoo",
          "arquivo.pt",
          "arquivo-web-crawler",
          "Aspiegel",
          "ASPSeek",
          "Asterias",
          "Atomseobot",
          "Attach",
          "autoemailspider",
          "AwarioRssBot",
          "AwarioSmartBot",
          "axios/0.21.4",
          "BackDoorBot",
          "Backlink-Ceck",
          "BackStreet",
          "BackWeb",
          "Badass",
          "Bandit",
          "Barkrowler",
          "BatchFTP",
          "Battleztar Bazinga",
          "BBBike",
          "BDCbot",
          "BDFetch",
          "BetaBot",
          "Bigfoot",
          "Bitacle",
          "Black Hole",
          "Blackboard",
          "BlackWidow",
          "BLEXBot",
          "Blow",
          "BlowFish",
          "Boardreader",
          "Bolt",
          "BotALot",
          "Brandprotect",
          "Brandwatch",
          "Buck",
          "Buddy",
          "BuiltBotTough",
          "BuiltWith",
          "Bullseye",
          "BunnySlippers",
          "BuzzSumo",
          "Bytespider",
        ],
        disallow: "/",
      },
      {
        userAgent: [
          "cah.io.community",
          "Calculon",
          "CATExplorador",
          "CCBot",
          "Cegbfeieh",
          "CensysInspect",
          "check1.exe",
          "CheeseBot",
          "CherryPicker",
          "CheTeam",
          "ChinaClaw",
          "Chlooe",
          "Citoid",
          "Claritybot",
          "clark-crawler",
          "Cliqzbot",
          "coccocbot",
          "Cocolyzebot",
          "CODE87",
          "Cogentbot",
          "cognitiveseo",
          "cohere-ai",
          "Collector",
          "com.plumanalytics",
          "CommonCrawl",
          "Copier",
          "CopyRightCheck",
          "Copyscape",
          "Cosmos",
          "Craftbot",
          "crawl.sogou.com",
          "crawler.feedback",
          "crawler4j",
          "Crawling at Home Project",
          "CrazyWebCrawler",
          "Crescent",
          "Crescent Internet ToolPak HTTP OLE Control v.1.0",
          "CrunchBot",
          "CSHttp",
          "Curious",
          "Custo",
          "CyotekWebCopy",
          "DatabaseDriverMysqli",
          "DataCha0s",
          "dataforseo.com",
          "DBLBot",
          "demandbase-bot",
          "Demon",
          "Deusu",
          "Devil",
          "Diffbot",
          "Digincore",
          "DigitalPebble",
          "Dirbuster",
          "Disco",
          "Discobot",
          "Discoverybot",
          "Dispatch",
          "DittoSpyder",
          "DnBCrawler-Analytics",
          "DnyzBot",
          "DomainAppender",
          "DomainCrawler",
          "Domains Project",
          "DomainSigmaCrawler",
          "domainsproject.org",
          "DomainStatsBot",
          "DomCopBot",
          "Dotbot",
          "Download Wonder",
          "Dragonfly",
          "Drip",
          "DSearch",
          "DTS Agent",
          "EasyDL",
          "Ebingbong",
          "eCatch",
          "ECCP/1.0",
          "Ecxi",
          "EirGrabber",
          "EMail Siphon",
          "EMail Wolf",
          "EmailCollector",
          "EmailSiphon",
          "EmailWolf",
          "EroCrawler",
          "evc-batch",
          "Evil",
          "Exabot",
          "Express WebPictures",
          "ExtLinksBot",
          "Extractor",
          "ExtractorPro",
          "EyeNetIE",
          "Ezooms",
          "facebookscraper",
          "FDM",
          "FemtosearchBot",
          "FHscan",
          "Fimap",
          "FlashGet",
          "Flunky",
          "Foobot",
          "Freeuploader",
          "FrontPage",
          "Fuzz",
          "FyberSpider",
          "Fyrebot",
          "GeedoProductSearch",
          "Genieo",
          "GermCrawler",
          "Getintent",
          "GetRight",
          "GetWeb",
          "Go!Zilla",
          "Go-Ahead-Got-It",
          "gopher",
          "Gotit",
          "GoZilla",
          "Grabber",
          "GrabNet",
          "Grafula",
          "GrapeFX",
          "GrapeshotCrawler",
          "GridBot",
          "GT::WWW",
          "Haansoft",
          "HaosouSpider",
          "Harvest",
          "Havij",
          "HEADMasterSEO",
          "Heritrix",
          "Hloader",
          "HMView",
          "HonoluluBot",
          "HTMLparser",
          "HTTP::Lite",
          "httplib",
          "HTTrack",
          "Humanlinks",
          "HybridBot",
          "Iblog",
          "IDBot",
          "IDBTE4M",
          "Id-search",
          "IlseBot",
          "Image Fetch",
          "Image Sucker",
          "IndeedBot",
          "Indy Library",
          "InfoNaviRobot",
          "InfoTekies",
          "Intelliseek",
          "InterGET",
          "InternetSeer",
          "Iria",
          "IRLbot",
          "Iskanie",
          "IstellaBot",
          "instabid",
          "ips-agent",
          "isitwp.com",
          "iubenda-radar",
          "JamesBOT",
          "Jbrofuzz",
          "JennyBot",
          "JetCar",
          "Jetty",
          "JikeSpider",
          "JOC Web Spider",
          "Joomla",
          "Jorgee",
          "JustView",
          "Jyxobot",
          "Kenjin Spider",
          "Keybot Translation-Search-Machine",
          "Keyword Density",
          "Keyword Density/0.9",
          "Kinza",
          "Kozmosbot",
          "Lanshanbot",
          "Larbin",
          "Leap",
          "LeechFTP",
          "LeechGet",
          "LexiBot",
          "Lftp",
          "LibWeb",
          "libWeb/clsHTTP",
          "Libwhisker",
          "LieBaoFast",
          "Lightspeedsystems",
          "Likse",
          "Linkbot",
          "linkdexbot",
          "LinkextractorPro",
          "LinkpadBot",
          "LinkScan",
          "LinkScan/8.1a Unix",
          "LinksManager",
          "LinkWalker",
          "LinqiaMetadataDownloaderBot",
          "LinqiaRSSBot",
          "LinqiaScrapeBot",
          "Lipperhey",
          "Lipperhey Spider",
          "Litemage_walker",
          "Lmspider",
          "LNSpiderguy",
          "Ltx71",
          "LWP::Simple",
          "lwp-request",
          "lwp-trivial",
          "lwp-trivial/1.34",
          "Magnet",
          "Mag-Net",
          "magpie-crawler",
          "Mail.RU_Bot",
          "MarkMonitor",
          "MarkWatch",
          "Mass Downloader",
          "Masscan",
          "Mata Hari",
          "MauiBot",
          "Mb2345Browser",
          "MeanPath Bot",
          "Mediatoolkitbot",
          "mediawords",
          "MegaIndex.ru",
          "Metauri",
          "MFC_Tear_Sample",
          "MIDown tool",
          "MIIxpc",
          "MIIxpc/4.2",
          "MicroMessenger",
          "Minefield",
          "Mister PiX",
          "moget",
          "Mojeek",
          "Mojolicious",
          "MolokaiBot",
          "Morfeus Fucking Scanner",
          "MQQBrowser",
          "Mr.4x3",
          "MSFrontPage",
          "MSIECrawler",
          "Msrabot",
          "MTRobot",
          "muhstik-scan",
          "Musobot",
          "Name Intelligence",
          "Nameprotect",
          "Navroad",
          "NearSite",
          "Needle",
          "Nessus",
          "Net Vampire",
          "NetAnts",
          "Netcraft",
          "netEstate NE Crawler",
          "NetLyzer",
          "NetMechanic",
          "NetSpider",
          "Nettrack",
          "Netvibes",
          "NetZIP",
          "NICErsPRO",
          "Nibbler",
          "Niki-bot",
          "Nikto",
          "NimbleCrawler",
          "Nimbostratus",
          "Ninja",
          "Nmap",
          "Node/simplecrawler",
          "NPbot",
          "Nuclei",
          "Nutch",
          "oBot",
          "Octopus",
          "omgili",
          "omgilibot",
          "OnCrawl",
          "Openfind",
          "Openfind data gathere",
          "OpenLinkProfiler",
          "Openvas",
          "OrangeBot",
          "OrangeSpider",
          "OutclicksBot",
          "OutfoxBot",
          "page scorer",
          "PageAnalyzer",
          "PageGrabber",
          "PageScorer",
          "PageThing.com",
          "Pandalytics",
          "Panscient",
          "Papa Foto",
          "Pavuk",
          "pcBrowser",
          "PECL::HTTP",
          "PeoplePal",
          "Picscout",
          "Piepmatz",
          "Pimonster",
          "Pi-Monster",
          "Pixray",
          "PleaseCrawl",
          "plumanalytics",
          "Pockey",
          "POE-Component-Client-HTTP",
          "polaris version",
          "probe-image-size",
          "Probethenet",
          "ProPowerBot",
          "ProWebWalker",
          "Psbot",
          "Pu_iN",
          "Pump",
          "PxBroker",
          "PyCurl",
          "Quick-Crawler",
          "RankActive",
          "RankActiveLinkBot",
          "RankFlex",
          "RankingBot",
          "RankingBot2",
          "Rankivabot",
          "RankurBot",
          "RealDownload",
          "Reaper",
          "RebelMouse",
          "Recorder",
          "RedesScrapy",
          "RepoMonkey",
          "RepoMonkey Bait & Tackle/v1.01",
          "Re-re",
          "Ripper",
          "ripz",
          "RMA",
          "RocketCrawler",
          "Rogerbot",
          "RSSingBot",
          "s1z.ru",
          "SalesIntelligent",
          "satoristudio.net",
          "SBIder",
          "scalaj-http",
          "scan.lol",
          "ScanAlert",
          "Scanbot",
          "ScoutJet",
          "Scrapy",
          "ScreenerBot",
          "ScrepyBot",
          "Searchestate",
          "SearchmetricsBot",
          "Seekport",
          "SemanticJuice",
          "SentiBot",
          "seocompany.store",
          "SEOkicks",
          "SEOkicks-Robot",
          "SEOlyticsCrawler",
          "Seomoz",
          "SEOprofiler",
          "seoscanners",
          "SeoSiteCheckup",
          "seostar",
          "SEOstats",
          "sexsearcher",
          "Shodan",
          "SISTRIX",
          "Siphon",
          "Site Sucker",
          "Sitebeam",
          "sitechecker.pro",
          "SiteCheckerBotCrawler",
          "Siteimprove",
          "SiteLockSpider",
          "siteripz",
          "SiteSnagger",
          "SiteSucker",
          "Sitevigil",
          "SlySearch",
          "SmartDownload",
          "SMTBot",
          "Snake",
          "Snapbot",
          "Snoopy",
          "Sociscraper",
          "Sogou web spider",
          "sogouspider",
          "Sosospider",
          "Sottopop",
          "SpaceBison",
          "Spammen",
          "SpankBot",
          "Spanner",
          "Spbot",
          "Spinn3r",
          "SputnikBot",
          "spyfu",
          "Sqlmap",
          "Sqworm",
          "Steeler",
          "Stripper",
          "Sucker",
          "Sucuri",
          "SuperBot",
          "SuperHTTP",
          "Surfbot",
          "SurveyBot",
          "Suzuran",
          "Swiftbot",
          "sysscan",
          "Szukacz",
          "Szukacz/1.4",
          "T0PHackTeam",
          "T8Abot",
          "tAkeOut",
          "Teleport",
          "TeleportPro",
          "Telesoft",
          "Telesphoreo",
          "Telesphorep",
          "The Intraformant",
          "TheNomad",
          "Thumbor",
          "TightTwatBot",
          "Titan",
          "Toata",
          "toCrawl/UrlDispatcher",
          "Toweyabot",
          "Tracemyfile",
          "trendiction.com",
          "trendiction.de",
          "Trendictionbot",
          "True_Robot",
          "Turingos",
          "Turnitin",
          "TurnitinBot",
          "TwengaBot",
          "Twice",
          "Typhoeus",
          "ubermetrics-technologies.com",
          "UnisterBot",
          "Upflow",
          "URLy Warning",
          "Vacuum",
          "Vagabondo",
          "VB Project",
          "V-BOT",
          "VCI",
          "VCI WebViewer VCI WebViewer Win32",
          "VelenPublicWebCrawler",
          "VeriCiteCrawler",
          "VidibleScraper",
          "Virusdie",
          "VoidEYE",
          "Voil",
          "Voltron",
          "voyagerx.com",
          "vuhuvbot",
          "Wallpapers",
          "WallpapersHD",
          "WASALive-Bot",
          "WBSearchBot",
          "Web Collage",
          "Web Enhancer",
          "Web Fetch",
          "Web Image Collector",
          "Web Pix",
          "Web Sauger",
          "Web Sucker",
          "Webalta",
          "WebAuto",
          "WebBandit",
          "WebBandit/3.50",
          "WebCopier",
          "WEBDAV",
          "WebEnhancer",
          "WebFetch",
          "WebFuck",
          "webgains-bot",
          "WebGo IS",
          "WebImageCollector",
          "WebLeacher",
          "WebmasterWorldForumBot",
          "webmeup-crawler",
          "WebPix",
          "webpros.com",
          "webprosbot",
          "WebReaper",
          "WebSauger",
          "Webshag",
          "Website Quester",
          "WebsiteExtractor",
          "WebsiteQuester",
          "Webster",
          "Webster Pro",
          "WebStripper",
          "WebSucker",
          "WebWhacker",
          "WebZip",
          "WeSEE",
          "Wget",
          "Whack",
          "Whacker",
          "Whatweb",
          "Who.is Bot",
          "WISENutbot",
          "Widow",
          "WinHTTrack",
          "WiseGuys Robot",
          "Wonderbot",
          "Woobot",
          "Wotbox",
          "Wprecon",
          "WPScan",
          "WWW::Mechanize",
          "WWW-Collector-E",
          "WWW-Mechanize",
          "WWWOFFLE",
          "Xaldon WebSpider",
          "Xenu",
          "xpymep1.exe",
          "YoudaoBot",
          "Zade",
          "Zauba",
          "Zermelo",
          "Zeus",
          "zgrab",
          "Zitebot",
          "ZmEu",
          "ZoomBot",
          "ZoominfoBot",
          "ZumBot",
          "ZyBorg",
        ],
        disallow: "/",
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
